CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Countries" (
    "Id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "Name" varchar(450) NOT NULL,
    "ISO2" varchar(450) NOT NULL,
    "ISO3" varchar(450) NOT null--,
    --CONSTRAINT "PK_Countries" PRIMARY KEY ("Id")
);

CREATE TABLE "Cities" (
    --"Id" int GENERATED BY DEFAULT AS IDENTITY,
	"Id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "Name" varchar(450) NOT NULL,
    "Lat" decimal(7,4) NOT NULL,
    "Lon" decimal(7,4) NOT NULL,
    "CountryId" int NOT NULL,
    --CONSTRAINT "PK_Cities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cities_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Countries" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Cities_CountryId" ON "Cities" ("CountryId");

CREATE INDEX "IX_Cities_Lat" ON "Cities" ("Lat");

CREATE INDEX "IX_Cities_Lon" ON "Cities" ("Lon");

CREATE INDEX "IX_Cities_Name" ON "Cities" ("Name");

CREATE INDEX "IX_Countries_ISO2" ON "Countries" ("ISO2");

CREATE INDEX "IX_Countries_ISO3" ON "Countries" ("ISO3");

CREATE INDEX "IX_Countries_Name" ON "Countries" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220812141314_Initial', '9.0.1');

ALTER TABLE "Cities" ADD "Population" float NOT NULL DEFAULT 0.0;

CREATE INDEX "IX_Cities_Population" ON "Cities" ("Population");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220817165802_Migration1', '9.0.1');

--
-- EF Identity
-- 
CREATE TABLE "AspNetRoles" (
    "Id" varchar(450) NOT NULL,
    "Name" varchar(256),
    "NormalizedName" varchar(256),
    "ConcurrencyStamp" varchar(10485760),
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" varchar(450) NOT NULL,
    "UserName" varchar(256),
    "NormalizedUserName" varchar(256),
    "Email" varchar(256),
    "NormalizedEmail" varchar(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" varchar(10485760),
    "SecurityStamp" varchar(10485760),
    "ConcurrencyStamp" varchar(10485760),
    "PhoneNumber" varchar(10485760),
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" TIMESTAMPTZ,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" int NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" int NOT NULL,
    "RoleId" varchar(450) NOT NULL,
    "ClaimType" varchar(10485760),
    "ClaimValue" varchar(10485760),
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" int NOT NULL,
    "UserId" varchar(450) NOT NULL,
    "ClaimType" varchar(10485760),
    "ClaimValue" varchar(10485760),
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" varchar(450) NOT NULL,
    "ProviderKey" varchar(450) NOT NULL,
    "ProviderDisplayName" varchar(10485760),
    "UserId" varchar(450) NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" varchar(450) NOT NULL,
    "RoleId" varchar(450) NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" varchar(450) NOT NULL,
    "LoginProvider" varchar(450) NOT NULL,
    "Name" varchar(450) NOT NULL,
    "Value" varchar(10485760),
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName"); --WHERE AspNetRoles.NormalizedName IS NOT NULL;

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName"); --WHERE AspNetUsers.NormalizedUserName IS NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220821223510_Identity', '9.0.1');

ALTER TABLE "AspNetUsers" ADD "DisplayName" varchar(10485760) NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220825211328_DisplayName', '9.0.1');

--
-- Refresh Tokens
--
CREATE TABLE "RefreshTokens" (
    --"Id" int GENERATED BY DEFAULT AS IDENTITY,
	"Id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "Token" varchar(10485760) NOT NULL,
    "Expires" timestamptz NOT NULL,
    "Created" timestamptz NOT NULL,
    "CreatedByIp" varchar(10485760) NOT NULL,
    "Revoked" timestamptz,
    "RevokedByIp" varchar(10485760),
    "ReplacedByToken" varchar(10485760),
    "ReasonRevoked" varchar(10485760),
    "UserId" varchar(450) NOT null,
    --CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220919024852_RefreshTokens', '9.0.1');

ALTER TABLE "Cities" ADD "AdminRegionId" int;

ALTER TABLE "Cities" ADD "Capital" varchar(450);

ALTER TABLE "Cities" ADD "SimpleMapsId" bigint NOT NULL DEFAULT 0;

CREATE TABLE "AdminRegions" (
    --"Id" int GENERATED BY DEFAULT AS IDENTITY,
	"Id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "Name" varchar(450) NOT NULL,
    "Code" varchar(450),
    "CountryId" int NOT NULL,
    --CONSTRAINT "PK_AdminRegions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AdminRegions_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Countries" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Cities_AdminRegionId" ON "Cities" ("AdminRegionId");

CREATE INDEX "IX_Cities_Capital" ON "Cities" ("Capital");

CREATE INDEX "IX_Cities_SimpleMapsId" ON "Cities" ("SimpleMapsId");

CREATE INDEX "IX_AdminRegions_Code" ON "AdminRegions" ("Code");

CREATE INDEX "IX_AdminRegions_CountryId" ON "AdminRegions" ("CountryId");

CREATE INDEX "IX_AdminRegions_Name" ON "AdminRegions" ("Name");

ALTER TABLE "Cities" ADD CONSTRAINT "FK_Cities_AdminRegions_AdminRegionId" FOREIGN KEY ("AdminRegionId") REFERENCES "AdminRegions" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221212220346_AddAdminRegions', '9.0.1');

COMMIT;