using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorldCitiesAPI.Data.Entities
{
    [Table("Cities")]
    [Index(nameof(Name))]
    [Index(nameof(Lat))]
    [Index(nameof(Lon))]
    [Index(nameof(Population))]
    [Index(nameof(Capital))]
    [Index(nameof(SimpleMapsId))]
    public class City
    {
        #region Properties
        /// <summary>
        /// The unique id and primary key for this City
        /// </summary>
        [Key]
        [Required]
        public int Id { get; set; }

        /// <summary>
        /// City name (in UTF8 format)
        /// </summary>
        public string Name { get; set; } = null!;

        /// <summary>
        /// City Latitude
        /// </summary>
        [Column(TypeName = "decimal(7,4)")]
        public decimal Lat { get; set; }

        /// <summary>
        /// City Longitude
        /// </summary>
        [Column(TypeName = "decimal(7,4)")]
        public decimal Lon { get; set; }

        /// <summary>
        /// City Population
        /// </summary>
        public double Population { get; set; }

        /// <summary>
        /// Blank if not a capital. otherwise:
        /// primary - country's capital (e.g. Washington D.C.)
        /// admin - first-level admin capital (e.g. Little Rick, AR)
        /// minor - lower-level admin capital (e.g. Fayetteville, AR)
        /// </summary>
        public string? Capital { get; set; } = null!;

        /// <summary>
        /// A 10 digit unique id generated by SimpleMaps.
        /// </summary>
        public long SimpleMapsId { get; set; }

        /// <summary>
        /// The name of the highest level administration region of the city town
        /// (e.g. a US state or Canadian provice).  Possibly blank.
        /// </summary>
        [ForeignKey(nameof(AdminRegion))]
        public int? AdminRegionId { get; set; }

        /// <summary>
        /// Country Id (forein key)
        /// </summary>
        [ForeignKey(nameof(Country))]
        public int CountryId { get; set; }
        #endregion

        #region Navigation Properties
        /// <summary>
        /// The administration region related to this city.
        /// </summary>
        public AdminRegion? AdminRegion { get; set; } = null!;
        /// <summary>
        /// The country related to this city.
        /// </summary>
        public Country? Country { get; set; } = null!;
        #endregion
    }
}
